//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPlugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagerPlugins.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        internal static string ACTION_FREEZE {
            get {
                return ResourceManager.GetString("ACTION_FREEZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thaw.
        /// </summary>
        internal static string ACTION_THAW {
            get {
                return ResourceManager.GetString("ACTION_THAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thaw locked.
        /// </summary>
        internal static string ACTION_THAW_LOCKED {
            get {
                return ResourceManager.GetString("ACTION_THAW_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to proceed with.
        /// </summary>
        internal static string ACTION_WARNING {
            get {
                return ResourceManager.GetString("ACTION_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Freeze.
        /// </summary>
        internal static string DEEP_FREEZE {
            get {
                return ResourceManager.GetString("DEEP_FREEZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen.
        /// </summary>
        internal static string DEEP_FREEZE_FORZEN {
            get {
                return ResourceManager.GetString("DEEP_FREEZE_FORZEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unforzen.
        /// </summary>
        internal static string DEEP_FREEZE_UNFORZEN {
            get {
                return ResourceManager.GetString("DEEP_FREEZE_UNFORZEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;DEEP_FREEZE_PASSWORD&apos; environment variable is not set..
        /// </summary>
        internal static string ERROR_ENVIRONMENT_VARIABLE_NOT_SET {
            get {
                return ResourceManager.GetString("ERROR_ENVIRONMENT_VARIABLE_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        internal static string MENU_FREEZE {
            get {
                return ResourceManager.GetString("MENU_FREEZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thaw.
        /// </summary>
        internal static string MENU_THAW {
            get {
                return ResourceManager.GetString("MENU_THAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thaw locked.
        /// </summary>
        internal static string MENU_THAW_LOCKED {
            get {
                return ResourceManager.GetString("MENU_THAW_LOCKED", resourceCulture);
            }
        }
    }
}
